apply plugin: 'org.jetbrains.kotlin.jvm'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$version_kotlin"

    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = '17'
    }
}
