plugins {
    id 'com.android.application'
}

android {
    namespace "com.thekeval.guesser"
    compileSdk 36

    buildFeatures {
        dataBinding true
    }

    defaultConfig {
        applicationId "com.thekeval.guesser"
        minSdk 21
        targetSdk 36
        vectorDrawables.useSupportLibrary = true
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$version_kotlin"

    // Core
    implementation "androidx.core:core-ktx:$version_core"

    // Constraint Layout
    implementation "androidx.constraintlayout:constraintlayout:$version_constraint_layout"

    // Material Design
    implementation "com.google.android.material:material:$version_material"

    // Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:$version_navigation"
    implementation "androidx.navigation:navigation-ui-ktx:$version_navigation"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'


    // Lifecycle
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$version_lifecycle"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$version_lifecycle"
    // implementation 'androidx.navigation:navigation-compose:1.0.0-alpha04'

    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$version_coroutine"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$version_coroutine"




    implementation 'androidx.appcompat:appcompat:1.2.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}